"""Bounded local drafts for the owner-authorized two-pair batch; never publishes."""
import json,hashlib,time,fcntl
from pathlib import Path
from urllib.request import Request,urlopen
root=Path(__file__).resolve().parents[2]
lock=(root/'planning/ai-os/runs/worker.lock').open('a');fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB)
data=json.loads((root/'src/data/ecuador-destinations.json').read_text())
for slug in ['yasuni','tena']:
 d=next(x for x in data if x['slug']==slug)
 evidence={'yasuni':'Yasuni and the Napo corridor are a lodge and river-based rainforest comparison. Exact lodge location matters; do not assume every Napo lodge is inside Yasuni National Park. Verify transfers via Coca with the chosen operator, without flight schedules or times. The biosphere portal recommends regulated operators and certified local guides, and prohibits disturbing wildlife. Do not promote fishing or visits to uncontacted peoples.', 'tena':'Tena is a road-access base in Napo for town stays and nearby lodges. Municipal tourism material describes rafting on the Jatunyacu and Misahualli rivers. Route suitability, conditions, equipment and guide assessment must be checked with qualified operators. Tena town is not equivalent to an isolated forest lodge. Nearby Misahualli is a different riverfront base.'}[slug]
 prompt=f'''Create English and idiomatic Spanish destination page copy for {slug}. Return JSON only with keys en and es. Each language object: quick (50 words), lede (35 words), fit (8 words), access (8 words), pace (8 words), sections (exactly 10 objects with heading, paragraphs [intro, practical context], display {{heading, intro, points: [three concise useful bullets]}}), faqs (six [question,answer] pairs). Target 950-1150 words per language counting quick, display intro/points and FAQs; 25-40 word FAQ answers. Match facts across languages. No HTML or links. Ten sections: landscape; traveler fit; access; length of stay; activities and wildlife; timing and conditions; choosing a base/lodge and guide; packing/mobility; respectful community and wildlife behavior; destination comparisons. Use destination-specific content, no generic Cuyabeno copy. A scenic editorial tone with practical decisions. Facts: {evidence}. Existing context: {json.dumps(d['en'])}. Never invent prices, travel times, operating schedules, permit rules, medical prescriptions, safety guarantees, sightings, reviews or firsthand experience. Three/four/five-day tradeoffs are editorial advice, not bookable packages. Ask operators for current conditions and exact facilities. Community visits require host consent. No species counts or superlatives. No ranking one destination as always cheaper.''' 
 key=hashlib.sha256(prompt.encode()).hexdigest()[:12];run=root/f'planning/ai-os/runs/{slug}/{key}';run.mkdir(parents=True,exist_ok=True)
 if (run/'draft.json').exists(): print(slug,'cache hit',flush=True);continue
 attempt=run/'attempt.json';count=json.loads(attempt.read_text())['count'] if attempt.exists() else 0
 if count>=2:raise ValueError('Attempt limit reached')
 attempt.write_text(json.dumps({'count':count+1}))
 start=time.monotonic();payload={'model':'qwen3.5:9b','messages':[{'role':'user','content':prompt}],'think':False,'stream':False,'format':'json','options':{'temperature':.2,'num_ctx':12288,'num_predict':10000}}
 with urlopen(Request('http://127.0.0.1:11434/api/chat',data=json.dumps(payload).encode(),headers={'Content-Type':'application/json'}),timeout=900) as response:r=json.load(response)
 draft=json.loads(r['message']['content']);assert all(len(draft[l]['sections'])==10 and len(draft[l]['faqs'])==6 for l in ['en','es'])
 (run/'draft.json').write_text(json.dumps(draft,ensure_ascii=False,indent=2)+'\n');(run/'status.json').write_text(json.dumps({'job':slug,'status':'awaiting_editorial_review','model':'qwen3.5:9b','seconds':round(time.monotonic()-start,2),'prompt_eval_count':r.get('prompt_eval_count'),'eval_count':r.get('eval_count'),'cloud_worker_tokens':0},indent=2)+'\n');print(slug,str(run),flush=True)
