"""Recorded supervisor corrections; never overwrite the original model output."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[2]
run=next((root/'planning/ai-os/runs/cuyabeno').glob('*'))
d=json.loads((run/'en.json').read_text())
d['quick']="Cuyabeno is an Ecuador Amazon destination for travelers who want canoe exploration, seasonally flooded forest and lagoon scenery. A common approach from Quito continues through Lago Agrio, then by road to a river entry and onward by canoe. The exact journey depends on the lodge and current arrangements. Wildlife observation takes patience; neither dolphins nor any other animal can be promised. Compare guides, group size, room conditions and transfer inclusions before choosing. Four or five days can leave more room for activities than a short visit, but count arrival and departure days carefully."
d['sections'][0]['paragraphs']=[
"Cuyabeno's appeal begins with the relationship between forest and water. Ecuador's tourism ministry describes seasonally flooded forest, lagoons and river landscapes, including Laguna Grande. This gives a canoe-based visit a different character from a trip focused mainly on forest trails. You may spend substantial time observing the edges of waterways, listening for birds and moving between habitats with a guide. The exact lodge zone matters: a name on a booking page does not tell you which channels, trails or lagoons your itinerary will reach.",
"Water levels can change what a route looks like and how it is navigated. Ask the operator what conditions mean for the proposed activities rather than choosing a date from a generic wet-versus-dry calendar. A landscape photograph is useful context, not a promise that your visit will look identical. The practical reason to choose Cuyabeno is an interest in this water-and-forest setting, supported by a guiding program that gives you time to observe it."
]
d['sections'][1]['paragraphs']=[
"Cuyabeno is a good fit if you enjoy guided nature outings, time in small boats and a lodge-based stay away from a city. Warmth, humidity, rain and muddy trails belong in the decision, alongside wildlife interests. Compare actual room facilities if comfort is important: electricity hours, ventilation, bathrooms, hot water and insect screening are property-specific. A traveler interested in birds or photography should ask about guide knowledge, excursion pace and whether the group can spend time observing without rushing.",
"It may be a poor fit if you have very little time, require reliable connectivity for work, or cannot comfortably manage the proposed boat boarding and walks. These are reasons to ask detailed questions, not to assume every property has the same limitations. Tena or Misahuallí may offer a more flexible road-based itinerary; Yasuní and the Napo corridor offer a different lodge and access choice. No alternative guarantees infrastructure, easy travel or sightings. Choose the verified itinerary that matches your requirements."
]
d['sections'][2]['paragraphs']=[
"Plan the entire journey from Quito, not just the final canoe transfer. The official tourism descriptions use Lago Agrio and the road toward Tarapoa and the Cuyabeno River as a common approach, followed by river travel. Your operator should confirm the actual meeting point, departure date, road transfer and lodge arrival sequence. Do not assume a flight exists because an older guide mentions air access. Check current transport arrangements directly, including how an overnight bus or an early departure affects sleep and arrival-day energy.",
"Ask who is responsible for each leg and what happens if an incoming connection is late. Confirm whether Quito transport is included, where luggage is stored, what waterproof protection is provided and whether meals are available during the journey. River duration varies with water conditions and the lodge's location, so avoid treating a quoted time as guaranteed. Leave a buffer before an onward flight or an important appointment. Request written instructions and an emergency contact you can access offline."
]
d['sections'][3]['paragraphs'][1]="Four- and five-day plans can leave more space for repeated outings and a less compressed pace, provided they include additional full activity days. Compare the actual arrival and departure times: an extra calendar day is not automatically an extra day in the forest. More time may allow a different trail, another early canoe outing or a pause when weather changes a plan. It improves opportunity rather than guaranteeing sightings. A longer stay can still be worthwhile beyond five days if it suits your interests, guide program and budget; there is no universal point at which extra time stops being useful."
d['sections'][4]['paragraphs']=[
"Canoe trips and guided walks are complementary ways to experience Cuyabeno. A boat outing may focus on lagoon edges, waterways and quiet wildlife observation; a forest walk may focus on plants, tracks, insects and the guide's interpretation. Night outings offer a different perspective but should follow the operator's current safety assessment. Ask whether boats use motors or paddles for each activity, how many guests share a guide, and whether the itinerary has time to stop rather than simply moving between scheduled attractions.",
"Official tourism material names birds, caimans and river dolphins among the region's wildlife. Presence in the region does not mean an animal will appear near your lodge or during your stay. Avoid packages that promise a particular sighting. Good guiding can help you recognize calls, understand behavior and appreciate smaller details even when large animals are absent. Binoculars and patience are useful; close pursuit, feeding and touching are not. Photography should follow the same distance and disturbance rules as ordinary observation."
]
d['sections'][6]['paragraphs']=[
"Compare the complete stay rather than a headline price or a room photograph. Ask for the exact lodge location, transfer sequence, guide language, maximum group size and sample activity schedule. Clarify whether guests from different arrival dates share excursions and whether a private guide is available. Check room screening, ventilation, bathroom arrangements, electricity hours and drinking-water provision. Recent reviews can help identify questions, but they do not replace written confirmation of the facilities and services included in your own booking.",
"Request a clear list of included meals, transfers, equipment and activities, together with any additional fees, drinks or optional visits. Confirm whether boots and rain protection are supplied and in which sizes. Ecuador's tourism ministry recommends registered operators and licensed guides; ask how you can verify those credentials. Also ask about boat safety equipment, emergency arrangements and cancellation terms. A claim of being sustainable should have an explanation: local employment, community participation and waste handling are useful subjects to discuss, not labels to accept without evidence."
]
d['sections'][7]['paragraphs']=[
"Pack for humidity, rain and a journey involving boats. Lightweight clothing that dries readily, rain protection, suitable footwear, a hat and sealed protection for documents and electronics are practical starting points. Ask the operator what footwear works on its trails and whether boots are supplied. A small day bag, binoculars and a torch may be useful for planned outings. Protect cameras from water and condensation, and allow space for damp items without soaking everything else. Confirm baggage limits with the actual transfer provider.",
"Discuss mobility needs before booking, including boat entry, steps, trail surfaces, walking duration, bathrooms and room access. Do not infer accessibility from a property photo or assume adapted equipment exists. Request information specific to your needs and, where possible, recent photographs of the relevant facilities. Review current official travel and health guidance and consult a qualified travel-health professional about personal preparation. Ask the operator about communication and evacuation arrangements. Keep essential personal supplies accessible; this guide does not prescribe vaccinations, medications or treatment."
]
d['sections'][8]['paragraphs'][0]="A community visit should be chosen and hosted by the community, with clear expectations about what visitors are invited to do. Ask who leads the experience, who receives payment and whether participation is optional. Do not treat people's homes, knowledge or ceremonies as attractions available on demand. Follow the host's rules and request permission before photographs, recordings or sharing identifying details. A description of cultural exchange does not establish that every lodge has the same relationships or that a particular activity will be available."
d['sections'][9]['paragraphs']=[
"Choose between Ecuador Amazon destinations by comparing the actual route and experience. Cuyabeno is associated with seasonally flooded forest and canoe exploration. Yasuní and the Napo corridor offer a different lodge-centered comparison, where the exact location and river approach deserve close attention. Tena is a road-access gateway with a broader choice of bases and excursions. Misahuallí is a smaller riverfront gateway near Tena; it should not be described as a cloud-forest destination. Puyo is a central Amazon gateway whose forest immersion depends on the onward activity or stay.",
"These distinctions help frame questions, but they do not rank every lodge or itinerary. Compare door-to-door time, full activity days, guide structure, comfort and total inclusions across the options you are actually considering. Avoid assuming Cuyabeno is always cheaper or that Yasuní is always more remote: property location and logistics matter. If you want a short extension, examine whether the transfers leave enough time outside. If wildlife observation is the priority, ask how the program supports patient repeated outings rather than counting promised species."
]
d['faqs'][3]=["What should I confirm before booking?","Ask the operator to explain registration, guide credentials, reserve-entry arrangements and any fees. Obtain written meeting instructions and inclusions for your itinerary. Requirements and services should be checked directly; this guide does not establish a universal permit rule for every visitor or route."]
(run/'en-reviewed.json').write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
