import test from 'node:test';
import assert from 'node:assert/strict';
import {handleContact} from '../functions/api/contact.js';
const origin='https://staging.experiencetheamazon.com';
const env={CONTACT_ENABLED:'true',TURNSTILE_SITE_KEY:'site',TURNSTILE_SECRET_KEY:'secret',BREVO_API_KEY:'test',CONTACT_FROM:'sender@example.com',CONTACT_TO:'owner@example.com'};
const payload={first_name:'Test',last_name:'Visitor',email:'visitor@example.com',country:'ecuador',travelers:'2',phone:'',start_date:'2099-01-01',end_date:'2099-01-02',interests:'Birdwatching',language:'en',privacy_consent:'yes',website:'','cf-turnstile-response':'token'};
const request=(p=payload,headers={})=>new Request(origin+'/api/contact',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...headers},body:JSON.stringify(p)});
const proof={success:true,hostname:new URL(origin).hostname,action:'contact'};
const mock=(verification=proof,email={messageId:'queued-id'},status=201)=>{const calls=[];return {calls,send:async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});return Response.json(calls.length===1?verification:email,{status:calls.length===1?200:status});}}};
test('disabled config exposes no secret and accepts no submissions',async()=>{const r=await handleContact(new Request(origin+'/api/contact'),{});assert.deepEqual(await r.json(),{enabled:false,siteKey:null});assert.equal((await handleContact(request(),{})).status,503);});
test('cross origin and wrong host rejected',async()=>{assert.equal((await handleContact(request(payload,{Origin:'https://evil.example'}),env)).status,403);assert.equal((await handleContact(new Request('https://experiencetheamazon.com/api/contact'),env)).status,403);});
test('missing consent, invalid fields, honeypot, missing token rejected without network',async()=>{for(const p of [{...payload,privacy_consent:'no'},{...payload,email:'bad'},{...payload,website:'spam'},{...payload,travelers:'1.5'},{...payload,'cf-turnstile-response':''},{...payload,interests:'x'.repeat(4001)}])assert.equal((await handleContact(request(p),env,()=>{throw Error('unexpected network');})).status,400);});
test('failed token, wrong hostname, wrong action never reach email',async()=>{for(const p of [{...proof,success:false},{...proof,hostname:'evil.example'},{...proof,action:'login'}]){const m=mock(p);assert.equal((await handleContact(request(),env,m.send)).status,400);assert.equal(m.calls.length,1);}});
test('Brevo error or missing message ID cannot show success',async()=>{for(const [result,status] of [[{},201],[{messageId:'x'},500]]){const m=mock(proof,result,status);assert.equal((await handleContact(request(),env,m.send)).status,502);}});
test('verified inquiry is sent only to configured recipient with reply-to and queued status',async()=>{const m=mock();const r=await handleContact(request(),env,m.send);assert.deepEqual(await r.json(),{ok:true,status:'queued'});assert.deepEqual(m.calls[1].body.to,[{email:env.CONTACT_TO}]);assert.equal(m.calls[1].body.replyTo.email,payload.email);assert.ok(!m.calls[1].body.textContent.includes('token'));});
test('oversized request is rejected',async()=>{assert.equal((await handleContact(request({...payload,interests:'x'.repeat(18000)}),env)).status,413);});
test('service outage fails closed',async()=>{assert.equal((await handleContact(request(),env,async()=>{throw Error('offline');})).status,502);});

test('production requires explicit hostname configuration and matching verification',async()=>{const prod='https://experiencetheamazon.com';const r=new Request(prod+'/api/contact',{method:'POST',headers:{Origin:prod,'Content-Type':'application/json'},body:JSON.stringify(payload)});const m=mock({...proof,hostname:'experiencetheamazon.com'});assert.equal((await handleContact(r,{...env,CONTACT_HOSTNAME:'experiencetheamazon.com'},m.send)).status,200);});

test('both name fields required and bounded',async()=>{for(const p of [{...payload,first_name:''},{...payload,last_name:' '},{...payload,first_name:'x'.repeat(81)},{...payload,last_name:'x'.repeat(121)}]) assert.equal((await handleContact(request(p),env,()=>{throw Error('unexpected network');})).status,400);});
test('all eight Amazon countries accepted after valid verification',async()=>{for(const country of ['ecuador','peru','brazil','colombia','bolivia','guyana','suriname','venezuela']){const m=mock();assert.equal((await handleContact(request({...payload,country}),env,m.send)).status,200);assert.equal(m.calls[1].body.subject,'Amazon trip inquiry · '+country[0].toUpperCase()+country.slice(1));}});
test('first letter capitalized without changing remainder of each name',async()=>{const m=mock();await handleContact(request({...payload,first_name:'  élise ',last_name:' mcDonald '}),env,m.send);assert.equal(m.calls[1].body.replyTo.name,'Élise McDonald');assert.ok(m.calls[1].body.textContent.includes('First name: Élise\nLast name: McDonald'));});

test('configured Turnstile can render while email delivery stays disabled',async()=>{const e={TURNSTILE_SITE_KEY:'public-key',TURNSTILE_SECRET_KEY:'secret'};assert.deepEqual(await (await handleContact(new Request(origin+'/api/contact'),e)).json(),{enabled:false,siteKey:'public-key'});assert.equal((await handleContact(request(),e)).status,503);});

test('missing, invalid, past and reversed dates rejected before network',async()=>{for(const p of [{...payload,start_date:''},{...payload,end_date:''},{...payload,start_date:'2000-01-01'},{...payload,start_date:'2099-02-30'},{...payload,end_date:'2098-12-31'}])assert.equal((await handleContact(request(p),env,()=>{throw Error('unexpected network');})).status,400);});
test('today, same-day end, 99 guests and optional phone accepted',async()=>{const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Guayaquil',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const part=t=>parts.find(p=>p.type===t).value;const today=part('year')+'-'+part('month')+'-'+part('day');for(const phone of ['', '+593 99 123 4567']){const m=mock();assert.equal((await handleContact(request({...payload,start_date:today,end_date:today,travelers:'99',phone}),env,m.send)).status,200);assert.ok(m.calls[1].body.textContent.includes('Start date: '+today));}});
test('guests exclude zero, decimals and three digits; phone length bounded',async()=>{for(const p of [{...payload,travelers:'0'},{...payload,travelers:'100'},{...payload,travelers:'1.5'},{...payload,phone:'x'.repeat(33)}])assert.equal((await handleContact(request(p),env,()=>{throw Error('unexpected network');})).status,400);});

 test('branded inquiry escapes visitor HTML and includes Instagram', async()=>{const {inquiryHtml}=await import('../functions/api/contact.js');const html=inquiryHtml({...payload,interests:'<img src=x onerror=alert(1)>'});assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));assert.ok(html.includes('https://www.instagram.com/experienceamazon/'));});
